[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[profile.hw02]
src = '02-week/hw'
out = 'out'
libs = ['lib']
test = 'test/02-week'

[profile.hw02_project]
src = 'src'
out = 'out'
libs = ['lib']

[fuzz]
runs = 300
solc = "0.8.17"
