[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[profile.hw01]
src = '01-week/hw'
out = 'out'
libs = ['lib']
test = 'test/01-week'

[profile.hw01_foundry_template]
src = '01-week/hw/Homework04/foundry-template-demo/src'
out = 'out'
libs = ['01-week/hw/Homework04/foundry-template-demo/lib']
test = '01-week/hw/Homework04/foundry-template-demo/test'

[profile.hw01_ctf]
src = '01-week/hw/Homework04/ctf'
out = 'out'
libs = ['lib']
test = 'test/01-week'
gas_reports = ["CTF_4_00", "CTF_4_01"]

[profile.hw02]
src = '02-week/hw'
out = 'out'
libs = ['lib']
test = 'test/02-week'

[profile.hw02_assembly]
src = '02-week/hw/assembly'
out = 'out'
libs = ['lib']
test = 'test/02-week'

[profile.hw02_notes]
src = '02-week/notes'
out = 'out'
libs = ['lib']
test = 'test/02-week'

[profile.hw02_gas_project]
src = '02-week/project/gas-optimization-foundry/src'
out = 'out'
libs = ['lib']
test = '02-week/project/gas-optimization-foundry/test'
gas_reports = ["GasContract", "original__GasContract"]

[profile.hw10]
src = '10-week/hw'
out = 'out'
libs = ['lib']
test = 'test/03-week'
gas_reports = ["Homework10_02a", "Homework10_02b"]

[profile.notes04]
src = '04-week/notes'
out = 'out'
libs = ['lib']
test = 'test/04-week'
gas_reports = ["SignatureNotes"]



[fuzz]
runs = 300
solc = "0.8.17"
