[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[profile.hw02_project]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ['Intro', 'Level_0_Solution_01','Level_0_Solution_02', 'Homework02', 'Level_0_Solution', 'Level_0_Solution1']

[fuzz]
runs = 300
solc = "0.8.17"
